apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediawiki.fullname" . }}-db
  labels:
    app: {{ template "mediawiki.name" . }}-db
    {{- include "mediawiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    app: {{ template "mediawiki.name" . }}-db
    {{- include "mediawiki.selectorLabels" . | nindent 4 }}
