apiVersion: v1
kind: Secret
metadata:
  name: db-env
  labels:
    app: {{ template "mediawiki.name" . }}
    chart: {{ template "mediawiki.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
    MARIADB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
    MARIADB_ROOT_PASSWORD: {{ .Values.db.root_password | b64enc | quote }}
